version: "3"
services:
  directus:
    image: directus/directus:11.0.2
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
    environment:
      SECRET: "u21736hn1236g71b4714v671b"
      ADMIN_EMAIL: "admin@example.com"
      ADMIN_PASSWORD: "admin098"
      DB_CLIENT: "sqlite3"
      DB_FILENAME: "/directus/database/data.db"
      WEBSOCKETS_ENABLED: "true"